
import { GoogleGenAI, Type } from "@google/genai";
import type { Slide } from '../types';

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const slideSchema = {
  type: Type.OBJECT,
  properties: {
    title: {
      type: Type.STRING,
      description: "A concise and engaging title for the slide."
    },
    content: {
      type: Type.ARRAY,
      items: {
        type: Type.STRING,
      },
      description: "An array of strings, where each string is a bullet point or a short sentence for the slide content. Maximum 6 items."
    },
    layout: {
      type: Type.STRING,
      description: "A suggested layout for the slide, e.g., 'Title and Content', 'Image with Caption', 'Title Only'."
    },
    imagePrompt: {
      type: Type.STRING,
      description: "A descriptive prompt for an AI image generator to create an illustration for the slide. The prompt must be generated by analyzing the slide title and content to determine the best visual representation. It must specify a style that is appropriate for the grade level and subject (e.g., 'colorful and simple' for young children, 'detailed and scientific' for advanced students). The prompt should focus on clear, detailed, and accurate visual representations that help explain the concept."
    },
    speakerNotes: {
      type: Type.STRING,
      description: "Detailed speaker notes for the teacher to read while presenting this slide. These notes should elaborate on the bullet points, provide additional context, examples, or explanations to help the teacher deliver a comprehensive lesson. They should be written in a conversational but educational tone."
    },
  },
  required: ["title", "content", "layout", "imagePrompt", "speakerNotes"]
};

export const generateSlidesFromDocument = async (
  topic: string,
  gradeLevel: string,
  subject: string,
  sourceMaterial: string,
  numSlides: number,
  useWebSearch: boolean = false,
  temperature: number = 0.7
): Promise<Slide[]> => {
  let prompt = `
    Based on the following topic, grade level, and subject, generate a slide deck presentation.

    **Topic:**
    ${topic}

    **Grade Level:**
    ${gradeLevel}

    **Subject:**
    ${subject}

    **Number of Slides:**
    ${numSlides}
    `;

  if (sourceMaterial) {
    prompt += `
    **Source Material:**
    ---
    ${sourceMaterial}
    ---
    `;
  }

  if (useWebSearch) {
    prompt += `
    **Web Search:**
    You have access to Google Search. Please use it to find the most up-to-date and relevant information to supplement the content, especially if the source material is missing details or if the topic requires current knowledge.
    `;
  }

  const totalSlides = numSlides + 1;

  prompt += `
    Please generate exactly ${totalSlides} slides.
    
    **SLIDE 1 MUST BE A TITLE SLIDE:**
    - **Title:** Use the provided Topic: "${topic}".
    - **Content:**
      - A catchy, short tagline related to the topic.
      - "${gradeLevel}"
      - "${subject}"
    - **Layout:** "Title Slide"
    - **Image Prompt:** Create a prompt for a visually striking title slide image that represents the overall topic.
    - **Speaker Notes:** Brief introductory remarks welcoming the class and introducing the topic.

    **SLIDES 2 to ${totalSlides}:**
    - Generate content slides covering the topic in a logical sequence.
    - For each slide, provide a title, content as bullet points (MAXIMUM 6 bullet points), a suggested layout, a prompt for an image generator, and detailed speaker notes.
    - ** IMPORTANT:** Do NOT use markdown formatting(like ** bold ** or * italic *) in the bullet points.Use plain text only.
    - ** IMPORTANT:** Do NOT use nested bullet points or sub - bullets.Each content item must be a single, standalone statement.
    
    ** CRITICAL REQUIREMENT FOR IMAGE PROMPTS:**

    For each slide, you must generate an imagePrompt by analyzing the slide's title and content to determine the best visual representation of the concept. The imagePrompt should describe what visual elements would best help a teacher explain the concept to students.

      ** Style Requirements:**
        - The style must be appropriate for the ** Grade Level ** and ** Subject **.
    - For younger students(e.g., K - 5), use styles like "colorful illustration", "simple diagram", or "cartoon style".
    - For older students(e.g., 6 - 12, University), use styles like "detailed diagram", "realistic illustration", "infographic", or "educational chart".
    - The visual should be clear, accurate, and educational.
    
    ** Content Requirements:**
    - The prompt should describe a visual representation that clearly explains the concept from the slide.
    - It must be detailed enough to be educational and helpful.
    - ** INCLUDE TEXT AND LABELS:** The illustration SHOULD include explanatory text, labels, and annotations where appropriate to enhance understanding.
    
    ** Examples of Good Prompts:**
    - (For 1st Grade Science): "A colorful, simple illustration showing the water cycle. A smiling sun shines on a blue ocean. Fluffy white clouds are in the sky. Rain falls from a grey cloud onto green grass. Arrows show the water going up and down."
      - (For University Biology): "A detailed, scientifically accurate cross-section diagram of a plant cell. Key structures like the cell wall, nucleus, chloroplasts, and large central vacuole are clearly illustrated and labeled. The style is educational and suitable for a textbook."
        - (For High School History): "A realistic historical illustration depicting the signing of the Declaration of Independence. The room is filled with colonial figures in period clothing. The atmosphere is serious and momentous."

          ** Examples of Bad Prompts:**
            - "Abstract representation of concepts"(too abstract)
            - "Minimalist icon of [concept]"(too simple, not educational)
            - "Simple decorative graphic"(not educational)
    
    Ensure the output is a valid JSON array of slide objects.Each object MUST have the following properties:
  - "title": string
    - "content": array of strings
      - "layout": string
        - "imagePrompt": string
          - "speakerNotes": string(Detailed speaker notes for the teacher. ** IMPORTANT:** At the very end of the speaker notes, add a section titled "Sources:".List the filenames of any source documents used and the URLs of any websites used from web search.If no specific sources were used for a slide, you may omit this section for that slide.)
    `;

  try {
    const tools: any[] = [];
    if (useWebSearch) {
      tools.push({ googleSearch: {} });
    }

    const config: any = {
      temperature: temperature,
      tools: tools.length > 0 ? tools : undefined,
    };

    // JSON mode is not supported with tools, so only use it when tools are not used
    if (tools.length === 0) {
      config.responseMimeType = "application/json";
      config.responseSchema = {
        type: Type.ARRAY,
        items: slideSchema
      };
    }

    const response = await ai.models.generateContent({
      model: "gemini-2.5-pro",
      contents: prompt,
      config: config,
    });

    let jsonText = response.text.trim();

    // Clean up markdown formatting if present (needed when not using JSON mode)
    if (jsonText.startsWith("```")) {
      jsonText = jsonText.replace(/^```json\s*/, "").replace(/^```\s*/, "").replace(/\s*```$/, "");
    }

    const slides: Slide[] = JSON.parse(jsonText);

    // Ensure speakerNotes exists for each slide
    slides.forEach(slide => {
      if (!slide.speakerNotes) {
        slide.speakerNotes = "Speaker notes were not generated for this slide.";
      }
    });

    return slides;

  } catch (error) {
    console.error("Error generating slides with Gemini API:", error);
    throw new Error("The AI model failed to generate a valid response.");
  }
};

export const generateImage = async (prompt: string, temperature: number = 0.3): Promise<Blob> => {
  try {
    // Use the provided prompt directly, as it should now contain specific style instructions
    const enhancedPrompt = `${prompt}

REQUIREMENTS:
- Create a high-quality illustration based on the description above.
- Ensure the style matches the description (e.g., cartoon, realistic, diagram).
- **INCLUDE TEXT:** The illustration SHOULD include clear, legible explanatory text, labels, and annotations where appropriate to enhance understanding.

PURPOSE: This illustration will be used by a teacher in a presentation slide. It should be a standalone educational resource that visually explains the concept to students.`;

    const response = await ai.models.generateContent({
      model: "gemini-3-pro-image-preview",
      contents: enhancedPrompt,
      config: {
        temperature: temperature,
      },
    });

    // Extract image data from response
    // Try different possible response structures
    const parts = (response as any).parts || (response as any).candidates?.[0]?.content?.parts || [];

    if (parts && parts.length > 0) {
      for (const part of parts) {
        // Try both camelCase and snake_case property names
        const inlineData = part.inlineData || part.inline_data;
        if (inlineData) {
          // Convert base64 to blob
          const base64Data = inlineData.data;
          const mimeType = inlineData.mimeType || inlineData.mime_type || 'image/png';

          // Convert base64 to binary
          const binaryString = atob(base64Data);
          const bytes = new Uint8Array(binaryString.length);
          for (let i = 0; i < binaryString.length; i++) {
            bytes[i] = binaryString.charCodeAt(i);
          }

          return new Blob([bytes], { type: mimeType });
        }
      }
    }

    // Log response structure for debugging if image not found
    console.error("Response structure:", JSON.stringify(response, null, 2));
    throw new Error("No image data found in response");
  } catch (error) {
    console.error("Error generating image with Gemini API:", error);
    throw new Error("Failed to generate image. Please try again.");
  }
};

export const regenerateImagePrompt = async (
  slideTitle: string,
  slideContent: string[],
  gradeLevel: string,
  subject: string,
  temperature: number = 0.7
): Promise<string> => {
  const prompt = `
    Generate a descriptive prompt for an AI image generator to create an illustration for the following presentation slide.
    
    **Slide Context:**
    - Title: "${slideTitle}"
    - Content: ${slideContent.join('; ')}
    - Grade Level: "${gradeLevel}"
    - Subject: "${subject}"
    
    **CRITICAL STYLE & CONTENT REQUIREMENTS:**
    
    **1. Style Requirements:**
    - The style must be appropriate for the **${gradeLevel}** and **${subject}**.
    - For younger students (e.g., K-5), use styles like "colorful illustration", "simple diagram", or "cartoon style".
    - For older students (e.g., 6-12, University), use styles like "detailed diagram", "realistic illustration", "infographic", or "educational chart".
    - The visual should be clear, accurate, and educational.
    
    **2. Content Requirements:**
    - The prompt should describe a visual representation that clearly explains the concept from the slide.
    - It must be detailed enough to be educational and helpful.
    - **INCLUDE TEXT AND LABELS:** The illustration SHOULD include explanatory text, labels, and annotations where appropriate to enhance understanding.
    
    **Examples of Good Prompts:**
    - (For 1st Grade Science): "A colorful, simple illustration showing the water cycle. A smiling sun shines on a blue ocean. Fluffy white clouds are in the sky. Rain falls from a grey cloud onto green grass. Arrows show the water going up and down."
    - (For University Biology): "A detailed, scientifically accurate cross-section diagram of a plant cell. Key structures like the cell wall, nucleus, chloroplasts, and large central vacuole are clearly illustrated and labeled. The style is educational and suitable for a textbook."
    - (For High School History): "A realistic historical illustration depicting the signing of the Declaration of Independence. The room is filled with colonial figures in period clothing. The atmosphere is serious and momentous."

    **Examples of Bad Prompts:**
    - "Abstract representation of concepts" (too abstract)
    - "Minimalist icon of [concept]" (too simple, not educational)
    - "Simple decorative graphic" (not educational)

    **Output:**
    Return ONLY the prompt text. Do not include any conversational text or labels like "Prompt:".
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-pro",
      contents: prompt,
      config: {
        temperature: temperature,
      },
    });

    return response.text.trim();
  } catch (error) {
    console.error("Error regenerating image prompt:", error);
    throw new Error("Failed to regenerate image prompt.");
  }
};

export const extractTextFromImage = async (base64Data: string, mimeType: string): Promise<string> => {
  const prompt = `
    Analyze this image and extract all visible text. 
    Also, provide a brief description of any diagrams, charts, or visual elements that convey information.
    Combine the extracted text and the visual description into a single coherent text block.
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-pro",
      contents: [
        {
          role: "user",
          parts: [
            { text: prompt },
            {
              inlineData: {
                mimeType: mimeType,
                data: base64Data
              }
            }
          ]
        }
      ]
    });

    return response.text.trim();
  } catch (error) {
    console.error("Error extracting text from image:", error);
    throw new Error("Failed to process image content.");
  }
};
