
import { GoogleGenAI, Type } from "@google/genai";
import type { Slide } from '../types';

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const slideSchema = {
  type: Type.OBJECT,
  properties: {
    title: {
      type: Type.STRING,
      description: "A concise and engaging title for the slide."
    },
    content: {
      type: Type.ARRAY,
      items: {
        type: Type.STRING,
      },
      description: "An array of strings, where each string is a bullet point or a short sentence for the slide content."
    },
    layout: {
      type: Type.STRING,
      description: "A suggested layout for the slide, e.g., 'Title and Content', 'Image with Caption', 'Title Only'."
    },
    imagePrompt: {
      type: Type.STRING,
      description: "A descriptive prompt for an AI image generator to create a textbook diagram style illustration for the slide. The prompt must be generated by analyzing the slide title and content to determine the best visual representation. It must specify 'textbook diagram style' to ensure scientific accuracy and educational precision. The prompt should focus on clear, detailed, professional, scientifically accurate visual representations that help explain the concept with textbook-quality precision. CRITICAL PROHIBITIONS: NO text, NO words, NO letters, NO numbers, NO labels, NO captions, NO text of any kind. NO abstract art, NO minimalist icons, NO decorative elements, NO flat design icons. The illustration must be purely visual, educational, and textbook-accurate, suitable for teachers to add text separately later."
    },
  },
  required: ["title", "content", "layout", "imagePrompt"]
};

export const generateSlidesFromDocument = async (
  sourceText: string,
  instructions: string,
  numSlides: number
): Promise<Slide[]> => {
  const prompt = `
    Based on the following source document and instructions, generate a slide deck presentation.

    **Instructions:**
    ${instructions}

    **Number of Slides:**
    ${numSlides}

    **Source Document:**
    ---
    ${sourceText}
    ---

    Please generate exactly ${numSlides} slides. For each slide, provide a title, content as bullet points, a suggested layout, and a prompt for an image generator.
    
    **CRITICAL REQUIREMENT FOR IMAGE PROMPTS:**
    
    For each slide, you must generate an imagePrompt by analyzing the slide's title and content to determine the best visual representation of the concept. The imagePrompt should describe what visual elements would best help a teacher explain the concept to students.
    
    **Style Requirements:**
    - ALWAYS use "textbook diagram style" as the consistent style terminology
    - The style must be clear, detailed, professional, scientifically accurate, and educationally precise
    - Focus on textbook-quality visuals with scientific accuracy and educational precision
    - The illustration should look like it belongs in a professional educational textbook
    
    **Content Requirements:**
    - The prompt should describe a scientifically accurate visual representation that clearly explains the concept from the slide
    - It must be detailed enough to be educational and helpful, with textbook-quality precision
    - The visual should be precise, accurate, and help teachers understand and present the concept correctly
    - Emphasize accuracy and precision in the visual representation
    
    **STRICTLY PROHIBITED:**
    - NO text, NO words, NO letters, NO numbers, NO labels, NO captions, NO text of any kind
    - NO abstract art, NO minimalist icons, NO decorative elements, NO flat design icons
    - NO symbols that could be mistaken for text
    
    **Purpose:**
    These illustrations will be used by teachers in presentation slides. Teachers will add text separately using text boxes. The illustration must be purely visual and educational, containing zero text.
    
    **Examples of Good Prompts:**
    - "A comprehensive educational illustration in textbook diagram style showing the complete water cycle. The scene features a bright sun shining over a large ocean. Visible vapor rises from the water's surface towards the sky. In the atmosphere, clouds are formed. Rain is shown falling from the clouds over a landmass with mountains and a river. The river flows across the land and back into the ocean, illustrating a continuous loop. The visual is clear, detailed, scientifically accurate, and professional. The illustration contains no text, no words, no numbers, and no labels of any kind."
    - "A detailed educational illustration in textbook diagram style focusing on the ground-level aspects of the water cycle. The image shows a cross-section of land. Rain is falling, with some water flowing over the surface towards a river (runoff), and some soaking into the earth to become groundwater. A close-up view of a plant clearly shows moisture being released from its leaves into the air (transpiration). The river is seen emptying into a larger body of water where collection occurs. The style is a professional textbook diagram, clear, scientifically accurate, and visually informative. The illustration contains no text, no words, no numbers, and no labels of any kind."
    - "An educational illustration in textbook diagram style of the solar system with planets in orbit around the sun, showing accurate relative sizes and distances, scientifically precise, no text or numbers"
    
    **Examples of Bad Prompts:**
    - "Abstract representation of concepts" (too abstract)
    - "Minimalist icon of [concept]" (too simple, not educational)
    - "Simple decorative graphic" (not educational)
    - "Educational diagram with labels showing [concept]" (contains labels/text)
    
    Ensure the output is a valid JSON array of slide objects.
    `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-pro",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: slideSchema
        },
        temperature: 0.7,
      },
    });

    const jsonText = response.text.trim();
    const slides: Slide[] = JSON.parse(jsonText);
    return slides;

  } catch (error) {
    console.error("Error generating slides with Gemini API:", error);
    throw new Error("The AI model failed to generate a valid response.");
  }
};

export const generateImage = async (prompt: string): Promise<Blob> => {
  try {
    // Comprehensive prompt enhancement for textbook-accurate educational illustrations without text
    const enhancedPrompt = `${prompt}

STYLE: Textbook diagram style. Professional, clear, detailed, scientifically accurate, and educationally precise. The illustration must look like it belongs in a professional educational textbook with textbook-quality accuracy and precision.

REQUIREMENTS:
- Scientifically accurate visual representation that clearly explains the concept
- Textbook-quality educational illustration suitable for classroom use
- Professional, clear, and precise visual design
- Detailed enough to be educational and informative with scientific accuracy
- Visual elements that are accurate and help teachers explain the concept correctly to students
- The illustration must be precise and accurate, matching the quality and accuracy of professional textbook diagrams

STRICTLY PROHIBITED:
- NO text, NO words, NO letters, NO numbers, NO labels, NO captions, NO text of any kind whatsoever
- NO abstract art, NO minimalist icons, NO decorative elements, NO flat design icons
- NO symbols that could be mistaken for text (like arrows pointing to labels, numbered items, etc.)
- NO speech bubbles, NO text boxes, NO annotations with text

PURPOSE: This illustration will be used by a teacher in a presentation slide. The teacher will add text separately using text boxes. The illustration must be purely visual and educational, containing absolutely zero text. It should help the teacher visually explain the concept to students.`;
    
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-image",
      contents: enhancedPrompt,
      config: {
        temperature: 0.3,
      },
    });

    // Extract image data from response
    // Try different possible response structures
    const parts = (response as any).parts || (response as any).candidates?.[0]?.content?.parts || [];
    
    if (parts && parts.length > 0) {
      for (const part of parts) {
        // Try both camelCase and snake_case property names
        const inlineData = part.inlineData || part.inline_data;
        if (inlineData) {
          // Convert base64 to blob
          const base64Data = inlineData.data;
          const mimeType = inlineData.mimeType || inlineData.mime_type || 'image/png';
          
          // Convert base64 to binary
          const binaryString = atob(base64Data);
          const bytes = new Uint8Array(binaryString.length);
          for (let i = 0; i < binaryString.length; i++) {
            bytes[i] = binaryString.charCodeAt(i);
          }
          
          return new Blob([bytes], { type: mimeType });
        }
      }
    }

    // Log response structure for debugging if image not found
    console.error("Response structure:", JSON.stringify(response, null, 2));
    throw new Error("No image data found in response");
  } catch (error) {
    console.error("Error generating image with Gemini API:", error);
    throw new Error("Failed to generate image. Please try again.");
  }
};
